name: publish puzzle package

on:
  push:
    branches:
      - develop
jobs:

  deploy-gh-pages:
    needs: ['publish-npm', 'publish-gpr']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: git config --global user.name "folland87"
      - run: git config --global user.email "frederic@olland.me"
      - run: git remote set-url origin https://github.com/folland87/puzzle.git
      - run: npm run deploy
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
